export const services = [
    {
        id: 1,
        name: 'Career',
        offers: [
            'resume review, proofread, and optimazation for ATS compatibility',
            'linkedIn profile review and optimization',
            'cover letter template creation',
            'job board onboarding, navigation assistance, and profile optimization',
            'networking stragtegy and outreach guidance',
            'coding bootcamp research & competitive analysis ranging from software developer to leadership roles',
            'spreadsheet tracking templates for job applications, interviews, and follow-ups',
        ],
    },
    {
        id: 2,
        name: 'Home',
        offers: [
            'organizing closets, cabinets, and storage spaces',
            'decluttering and donating unwanted items',
            'deep cleaning - dusting, sweeping, mopping, vacuuming, disinfecting ceiling to floor',
            'washing windows and mirrors',
            'moving assistance - packing, loading, unloading, unpacking, organizing',
            'assisting with home renovation projects',
            'doing and folding laundry, including ironing and steaming clothes',
            'creating cleaning schedules and checklists',
            'coordinating with contractors and service providers',
            'light yard work such as weeding, planting flowers, and general tidying',
            're-potting plants, both indoor and outdoor',
            'assembling furniture and home decor items',
            'hanging up pictures, shelves, curtains, and other wall-mounted items',
            'setting up smart home devices and systems - TVs, speakers, lights, projectors, Roku, Amazon Echo & Alexa, Firesticks, Google Home, ect',
            'eco-friendly home tips and product recommendations',
            'house sitting services including plant care, mail collection, pet care (see pet section)',
        ],
    },
    {
        id: 3,
        name: 'Pets',
        offers: [
            'dog walking and exercise',
            'pet sitting services including feeding, watering, and companionship',
            'grooming assistance such as brushing & bathing',
            'organizing pet supplies and creating storage solutions',
            'scheduling vet appointments and managing pet health records',
            'assisting with pet adoption research and processes',
            'transportation to and from vet appointments or grooming sessions',
        ],
    },
    {
        id: 4,
        name: 'Childcare',
        offers: [
            'babysitting services for children of various ages',
            'assisting with homework and educational activities',
            'organizing playdates and social activities',
            'creating schedules and routines for children',
            'preparing simple meals and snacks',
            'engaging in creative activities such as arts and crafts, reading, and outdoor play',
            'light housekeeping related to childcare, such as tidying up toys and cleaning up after meals',
        ]
    },
    {
        id: 5,
        name: 'Technology',
        offers: [
            'website audit and recommendations for improvement',
            'tech tool recommendations for small businesses or personal use',
            'basic troubleshooting for common tech issues',
            'guidance on setting up productivity tools and apps',
            'cleaning up email inboxes & unsubscribing from unwanted newsletters',
            'sending emails, setting up automations, and managing contacts',
            'organizing digital files and folders for easy access',
            'organizing social media accounts, blocking unwanted followers, and updating bios',
            'phone setup and optimization, including app recommendations and organization',
            'switching from Android to iPhone or vice versa',
            'switching from PC to Mac or vice versa',
            'switching phone service providers',
            'installing passwords managers and setting up secure passwords',
        ],
    },
    {
        id: 6,
        name: 'Travel',
        offers: [
            'researching destinations based on your interests and budget',
            'finding & booking the best flight, car rental, and hotel options and deals',
            'recommending accommodations that suit your preferences',
            'creating a detailed itinerary with activities and dining options',
            'creating a custom map with points of interest or activities',
            'providing packing lists tailored to your destination and activities',
            'offering travel tips and advice for a smooth trip',
            'driving to airport(s) (limited to 4 people) or scheduling rideshares'
        ],
    },
    {
        id: 7,
        name: 'Weddings',
        offers:[
            'researching venues, vendors, and services based on your preferences and budget',
            'creating checklists for 1 month, 3 months, 6 months, and 1 year before the wedding',
            'creating a detailed wedding day timeline and checklist',
            'coordinating with vendors and managing communication',
            'assisting with guest list management and RSVP tracking',
            'providing recommendations for wedding themes, decor, and activities',
            'offering tips for stress-free wedding planning and execution',
            'scheduling honeymoon, bachelor, and bachelorette trips (see travel section)',
            'helping with flower arrangements and decorations',
            'help with crafting wedding favors and invitations',
        ]
    },
    {
        id: 8,
        name: 'Money',
        offers: [
            'budget creation and management, snyncing bank accounts',
            'cashapp, venmo, paypal, zelle setup and optimization',
            'expense tracking and categorization',
            'savings goal setting and progress tracking',
            'bill payment reminders, automations, and organization',
            'organizing paper financial documents and statements',
        ],
    },
    {
        id: 9,
        name: 'Mail & Packages',
        offers: [
            'organizing and sorting physical mail and packages',
            'assisting with online order tracking and management',
            'coordinating package pickups and drop-offs',
            'helping with returns and exchanges for online purchases',
            'setting up notifications for important mail and package deliveries',
            'waiting at home for important deliveries or service appointments',
        ]
    },
    {
        id: 10,
        name: 'Fitness & Wellness',
        offers: [
            'recommending wellness apps and tools for tracking progress',
            'setting up accounts on fitness platforms and apps',
            'researching local fitness classes and wellness events',
            'researching gym memberships and personal trainers based on your goals and budget',
            'cancelling gym memberships',
            'compiliing healthy recipes and meal planning ideas',
            'i can swim! only freestyle stroke lessons available though :)',
        ]
    },
    {
        id: 11,
        name: 'Car',
        offers:[
            'scheduling regular maintenance appointments (oil changes, tire rotations, etc.)',
            'researching and recommending local mechanics and service centers',
            'organizing car documents and maintenance records',
            'setting up reminders for registration renewals and inspections',
            'assisting with car insurance research and comparisons',
            'bringing to drive through car washes or detail appointments',
            'washing car exterior, cleaning and vacuming interior',
        ]
    },
    {
        id: 12,
        name: 'Medical',
        offers:[
            'scheduling appointments with doctors, dentists, and specialists',
            'organizing medical records and documents',
            'transportation to and from medical appointments)',
            'setting up reminders for medication refills and appointments',
            'picking up prescriptions from local pharmacies',
            'calling insurance companies to verify coverage and benefits (and argue, who knows)',
            'researching healthcare providers and facilities based on your needs and location',
            'assisting with insurance paperwork and claims',
            'providing information on local health resources and support groups',
        ]
    },
    {   id: 13,
        name: 'Small Businesses',
        offers:[
            'social media account setup and optimization',
            'researching industry trends and competitors, and creating competitor analysis reports',
            'assisting with customer communication and support',
            'organizing digital files and documents',
            'setting up productivity tools and apps for team collaboration',
            'basic bookkeeping and expense tracking',
            'creating templates for invoices, contracts, and other business documents',
            'shipping and receiving assistance for online orders',
            'process improvement recommendations and implementation',
            'shopify store setup and optimization',
        ]
    },
    {
        id: 14,
        name: 'Other/Miscellaneous',
        offers:[
            'event planning and coordination for birthdays, anniversaries, and other special occasions',
            'gift research and purchasing based on recipient preferences and budget',
            'grocery shopping or pickup, meal prep assistance, and pantry organization',
            'assisting with personal projects such as scrapbooking, photo organization, or crafting',
            'organizing garage sales or online selling of unwanted items',
            'returning library books or other borrowed items',
        ]
    }
]