function About() {
  return (
    <div className='text-center'>
      <header className='text-4xl font-bold mb-3 dark:text-indigo-50'>what&apos;s with the re-brand?!</header>
      <p className='m-6 text-2xl dark:text-indigo-50'>for anybody visiting from linkedin, stumbled upon this through a google search, or maybe you&apos;re here because you took a deep dive into the internet & found yourself in a rabbit hole (those are kinda fun), what&apos;s up? so here&apos;s the deal: this blog hasn&apos;t always been like this. the look, feel, content, ect are all different. if you&apos;re wondering why, read on. if not, well hey! welcome, stay awhile, maybe drink some water, you&apos;re probably dehydrated!</p>
      <p className='m-6 text-2xl dark:text-indigo-50'>this blog originally started in the summer of 2021 as a way for me to challenge myself technically. while down one of <em>my</em> black hole searches, i came across a badass content management system - hygraph (formally graphcms) that was really easy to integrate into my website, lightweight, and last but certainly not least, wasn&apos;t wordpress. so, i started writing some tech content.</p>
      <p className='m-6 text-2xl dark:text-indigo-50'>lemme be very transparent here: it was a way for me to flex. i was looking for a job at the time, and writing about things that i was learning was a good way to show recruiters that i was actively contributing to something... anything. somewhere around early 2022, it started to feel less genuine, and after february, i completely stopped making posts. it became a chore to find something to write about, and i felt a pressure to write tutorials, write reviews of the tech i was using, create buzzfeed like articles like &apos;what you should know before you become this-type-of-developer&apos;, ect. tbh, that just isn&apos;t me. i like writing about my life. i like writing about things that challenge me, be it tech or something as unrelated to tech as learning how to swim laps.</p>
      <p className='m-6 text-2xl dark:text-indigo-50'>so while you may have ended up here because you&apos;re a developer and want some insight into how to learn about javascript or read a tutorial on integrating a database into your application, that&apos;s definitely not what i can offer all of the time. i&apos;m a person first. and writing is something i actually do enjoy, but i refuse to let the fact that i&apos;m a developer silo me into only writing about tech. it&apos;s not a genuine representation of all that i have to offer. there&apos;s so many ways that this career has pushed me to become a better person, and sharing some actual <em>life</em> experiences with you is more my jam. my style is more brene brown, than it is bill gates.</p>
      <p className='m-6 text-2xl dark:text-indigo-50'>i write with my heart, i include emojis (safely, i know screen readers hate that shit!), i swear a little too much, i don&apos;t always want to write about tech, and i LOVE telling really bad jokes poorly. so if that&apos;s <em>your</em> jam, please stay a while & enjoy!</p>
      <p className='m-6 text-2xl dark:text-indigo-50'>much love 💜 stay golden 🏆</p>
    </div>
  )
}

export default About;
